"""Render `runtime_matrix.json` as the markdown table the docs publish.

Split from the benchmark so the table can be reformatted without re-running six
hours of measurement, and so a merged JSON (the ORT CUDA rows come from a second
environment) renders in one pass.

    uv run examples/render_runtime_matrix.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = """# Latency: runtime x device x precision x input size

Generated by `examples/runtime_matrix.py`, rendered by `examples/render_runtime_matrix.py`.
Every row is measured on the machine described below; nothing here is quoted.

**Protocol.** Model inference only unless the row says `graph` under NMS: no
letterboxing, no host-side NMS, batch 1, single stream, synchronous, median of 30 runs
after 8 warmup runs discarded whole. Latency, not throughput — an async multi-stream
pipeline reports higher FPS on the same hardware. GPU work is synchronised before the
clock is read.

**NMS column.** `external` returns raw `[N, 4]` + `[N, 80]` tensors and leaves NMS to
the caller; `graph` is `--target end2end`, with NonMaxSuppression inside the graph, so
the row includes it. The two are not interchangeable — compare within a column.
"""

FOOTER = """
## Reproducing

```bash
uv sync --dev --extra onnx --extra openvino --extra tensorrt
uv run examples/runtime_matrix.py --models yolo_nas_s --sizes 320,640 \\
    --nms external,graph --calibration-dir ~/datasets/coco/images/val2017

# ONNX Runtime's CUDA provider needs the other wheel, which cannot coexist with the
# CPU one, so its rows come from a second pass that merges into the same JSON:
uv sync --dev --extra onnx-gpu --extra tensorrt
uv run examples/runtime_matrix.py --runtimes ort --sizes 320,640

uv run examples/render_runtime_matrix.py
```

## On comparing this with published leaderboards

Detection leaderboards usually report TensorRT latency on an NVIDIA T4 at batch 1.
That is not the hardware above, and a latency figure means nothing without its
protocol, so the two should not be read side by side.
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", default="docs/benchmarks/runtime_matrix.json")
    parser.add_argument("--output", default="docs/benchmarks/runtime_matrix.md")
    args = parser.parse_args()

    data = json.loads(Path(args.input).read_text())
    env, rows = data["environment"], data["rows"]

    lines = [HEADER, "**Machine.**\n"]
    for key in ("cpu", "gpu", "driver", "platform", "power_source", "python", "torch",
                "onnxruntime", "openvino", "tensorrt"):
        if key in env:
            lines.append(f"- `{key}`: {env[key]}")
    lines.append(
        "\nThe power source is recorded because it changes the answer: this laptop GPU is "
        "power-capped on battery, and the same pass runs materially slower there.\n"
    )

    measured = [r for r in rows if r["median_ms"] is not None]
    skipped = [r for r in rows if r["median_ms"] is None]

    for size in sorted({r["input"] for r in measured}):
        lines.append(f"\n## {size}x{size}\n")
        lines.append("| runtime | device | precision | NMS | median ms | FPS |")
        lines.append("|---|---|---|---|---:|---:|")
        block = [r for r in measured if r["input"] == size]
        for row in sorted(block, key=lambda r: r["median_ms"]):
            lines.append(
                f"| {row['runtime']} | {row['device']} | {row['precision'].upper()} | "
                f"{row['nms']} | {row['median_ms']:.2f} | {row['fps']:.1f} |"
            )

    if skipped:
        lines.append("\n## Not measured\n")
        lines.append("Recorded rather than dropped: a runtime missing from the environment is")
        lines.append("information, and a silent gap is not.\n")
        for row in sorted(skipped, key=lambda r: (r["runtime"], r["device"], r["precision"], r["input"])):
            lines.append(
                f"- **{row['runtime']} / {row['device']} / {row['precision'].upper()} / "
                f"{row['input']} / nms={row['nms']}** — {row['error']}"
            )

    lines.append(FOOTER)
    out = Path(args.output)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(measured)} measured, {len(skipped)} not)")


if __name__ == "__main__":
    main()
