"""Render the model table from what was measured, for the docs and the README.

Two runs feed it: `model_table.py` (accuracy, parameters, FLOPs) and
`runtime_matrix.py` (latency per runtime and device). Joining them here rather than
by hand is the point — the README's headline table is the one most likely to drift
from the measurement behind it.

    uv run examples/render_model_table.py
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

HEADER = """# Model table: accuracy, size and latency

Generated by `examples/render_model_table.py` from two measured JSONs, so every
column regenerates and any disagreement is reproducible:

```bash
uv run examples/model_table.py --coco ~/datasets/coco --input-size 640 --half --nms-iou 0.70
uv run examples/model_table.py --coco ~/datasets/coco --input-size 320 --half --nms-iou 0.70
uv run examples/runtime_matrix.py --models yolo_nas_s,yolo_nas_m,yolo_nas_l --sizes 320,640 \\
    --calibration-dir ~/datasets/coco/images/val2017 \\
    --sample-image ~/datasets/coco/images/val2017/000000435081.jpg
uv run examples/render_model_table.py
```
"""

SLUG = {"YOLO-NAS-S": "yolo_nas_s", "YOLO-NAS-M": "yolo_nas_m", "YOLO-NAS-L": "yolo_nas_l"}


def fastest(matrix_rows, model_slug, size, predicate):
    candidates = [
        r for r in matrix_rows
        if r["median_ms"] is not None and r["model"] == model_slug
        and r["input"] == size and r["nms"] == "external" and predicate(r)
    ]
    return min(candidates, key=lambda r: r["median_ms"])["median_ms"] if candidates else None


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--accuracy", default="docs/benchmarks/model_table.json")
    parser.add_argument("--matrix", default="docs/benchmarks/runtime_matrix.json")
    parser.add_argument("--output", default="docs/benchmarks/model_table.md")
    parser.add_argument("--readme-block", default=None, help="Also write just the headline table here.")
    args = parser.parse_args()

    rows = json.loads(Path(args.accuracy).read_text())
    matrix = json.loads(Path(args.matrix).read_text())
    matrix_rows, env = matrix["rows"], matrix["environment"]

    def cell(ms):
        """Latency with its reciprocal underneath. FPS carries no information a
        millisecond figure does not, and it is the one most readers think in."""
        return "—" if ms is None else f"{ms:.2f} ms<br><sub>{1000 / ms:.0f} FPS</sub>"

    headline = [
        "| Model | Input | Params | GFLOPs | AP | AP<sub>50</sub> | dGPU<br><sub>TensorRT FP16</sub> "
        "| CPU<br><sub>OpenVINO INT8</sub> | iGPU<br><sub>OpenVINO INT8</sub> |",
        "|:---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    detail = [
        "| Model | Input | Params | GFLOPs | AP | AP50 | AP75 | AP_S | AP_M | AP_L |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]

    for row in sorted(rows, key=lambda r: (list(SLUG).index(r["model"]), r["input_size"])):
        slug, size = SLUG[row["model"]], row["input_size"]
        trt = fastest(matrix_rows, slug, size, lambda r: r["runtime"] == "TensorRT" and r["precision"] == "fp16")
        cpu = fastest(matrix_rows, slug, size,
                      lambda r: r["runtime"] == "OpenVINO" and r["precision"] == "int8" and "Core" in r["device"])
        igpu = fastest(matrix_rows, slug, size,
                       lambda r: r["runtime"] == "OpenVINO" and r["precision"] == "int8" and "Iris" in r["device"])
        headline.append(
            f"| **{row['model']}** | {size} | {row['params_m']}M | {row['gflops']} | "
            f"{row['mAP']} | {row['mAP_50']} | {cell(trt)} | {cell(cpu)} | {cell(igpu)} |"
        )
        detail.append(
            f"| {row['model']} | {size} | {row['params_m']}M | {row['gflops']} | {row['mAP']} | "
            f"{row['mAP_50']} | {row['mAP_75']} | {row['mAP_small']} | {row['mAP_medium']} | {row['mAP_large']} |"
        )

    doc = [
        HEADER,
        "## Box AP on COCO val2017",
        "",
        *detail,
        "",
        "## With latency, per device",
        "",
        *headline,
        "",
        f"Latency is model inference only, batch 1, on {env.get('gpu', 'this machine')} and "
        f"{env.get('cpu', 'its CPU')}. FPS is `1000 / latency` on a single synchronous stream —",
        "**not throughput**, and not a whole frame, since preprocessing and NMS are excluded.",
        "The full grid — every runtime, precision and NMS placement — is in",
        "[the runtime matrix](runtime_matrix.md).",
        "",
        "## Protocol",
        "",
        "- **Weights**: the pretrained COCO checkpoints this library downloads, which originate",
        "  from Deci's super-gradients releases. Not weights trained by this project.",
        "- **Accuracy**: full COCO val2017, all 5000 images, `pycocotools`. Input letterboxed with",
        "  aspect preserved; NMS at confidence 0.001 and IoU 0.70, which a sweep found optimal.",
        "  Predictions are mapped back to original image coordinates before being compared with the",
        "  ground truth — the evaluator inverts the same letterbox the dataset applied, so a",
        "  non-640 input size is measured correctly rather than approximately.",
        "- **Accuracy is measured in FP32** even where the latency column is FP16. Whether",
        "  quantization costs AP is a separate question with its own script,",
        "  `examples/runtime_accuracy.py`, which evaluates the exported artifact itself.",
        "- **Parameters**: `sum(p.numel() for p in model.parameters())`.",
        "- **FLOPs**: `torch.utils.flop_counter` for one forward pass at the stated input size,",
        "  multiplies and adds counted separately. Papers reporting roughly half these figures are",
        "  counting multiply-accumulates; compare conventions before comparing numbers.",
        "",
        "## On comparing this with published leaderboards",
        "",
        "Detection leaderboards usually report latency on an NVIDIA T4 with TensorRT at batch 1.",
        "That is not the hardware above, and a latency number is meaningless without its protocol,",
        "so the two columns should not be read side by side. The accuracy columns are directly",
        "comparable.",
    ]

    out = Path(args.output)
    out.write_text("\n".join(doc) + "\n")
    print(f"wrote {out}")

    if args.readme_block:
        Path(args.readme_block).write_text("\n".join(headline) + "\n")
        print(f"wrote {args.readme_block}")
    else:
        print("\n" + "\n".join(headline))


if __name__ == "__main__":
    main()
